name: Slack Notification TEST
on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Fire Notification
        uses: myrealtrip/github-slack-boy@v1.8.0
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          github-token: ${{ secrets.GH_TOKEN }}
          channel-id: ${{ secrets.CHNNAL_ID }}
          user-info-url: ${{ secrets.USER_URL }}
          action-owner: ${{ github.actor }}
