name: Slack Notification TEST
on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Fire Notification
        uses: myrealtrip/github-slack-notify-action@v1.8.7
        with:
          plane-text: 테스트 메세지입니다.
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          github-token: ${{ secrets.GH_TOKEN }}
          channel-id: ${{ secrets.CHNNAL_ID }}
          user-info-url: ${{ secrets.USER_URL }}
          action-owner: ${{ github.actor }}
